### ISSUE TITLE
Login 기능을 갖고 싶사옵니다.

### ISSUE THREAD

**Issue by jshsakura** [tarpha/torrssen2#1]
먼저 좋은 프로그램 너무나 감사합니다. 
Login 기능을 간단하게 설정할수 있었으면 좋겠습니다.

**Comment by tarpha** [comment]
감사합니다. 
spring security만 넣으면 간단하게 되긴 합니다. 
단 로그인 사용여부를 같이 넣어야 할거 같아서
좀 볼께요.

**Comment by tarpha** [comment]
Login 기능 추가하였습니다.

**Comment by jshsakura** [comment]
너무나 감사합니다.

2019년 6월 16일 (일) 오후 10:44, JW.Lee <notifications@github.com>님이 작성:
