### ISSUE TITLE
자동 다운로드 관련

### ISSUE THREAD

**Issue by Lee-DongWoo** [tarpha/torrssen2#10]
안녕하세요.

저는 RSS사이트별로 각각의 다운로드 폴더를 구성하고, 모든 컨텐츠를 받으려고 하고있습니다.
자동관리 메뉴에서 '포함될 단어' 필드를 입력하지 않으면 제가 원하는데로 구성이 되지 않습니다.

자동 다운로드 관리 항목의 ID가 '포함될 단어' 필드 인거 같습니다.  
'포함될 단어' 없이 계속 추가해도, 1개 의 항목만이 계속 업데이트될 뿐입니다.
포함될 단어를 입력하지 않고 자동 다운로드 항목을 여러개 구성하고싶습니다.

현재 방법이 없는지 문의 드립니다.
확인 부탁드립니다.
감사합니다. ^^

**Comment by tarpha** [comment]
안녕하세요. 

RSS 리스트 관리에 전체 다운로드 기능이 있으며 폴더 별로 구분하여 다운받을 수 있습니다.
