### ISSUE TITLE
rss 링크 파싱 관련

### ISSUE THREAD

**Issue by bulzipke** [tarpha/torrssen2#11]
안녕하세요! 좋은 프로그램 개발해 주셔서 감사합니다.
다름이 아니라, 제가 사용하는 rss 는 다음과 같이 제공이 됩니다.
```
<item>
<title>샘플영화</title>
<link>https://막힌사이트.com/bbs/board.php?wr_id=1234</link>
<enclosure url="https://우회사이트.com/down/1234?token=abcdef" length="30" type="x-scheme-handler/magnet" />
</item>
```
vpn 이나 sni 등을 하지 않으면, 막힌사이트로 접근은 할 수 없고, 우회사이트를 통하면 접근이 되기에 enclosure url 을 트랜스미션으로 보내는 기능을 희망합니다.
꽤 마이너한 기능이겠지만;; rss 사이트 관리 페이지에 참조링크(default=link)란을 만들어, enclosure url 과 같이 다른 곳에 있는 주소를 참고할 수 있는 설정을 추가 할 수 있을지.. 궁금 합니다

**Comment by tarpha** [comment]
말씀하신 기능을 사용하려면  reflection을 써야합니다. 파서가 getter로 값을 가져오는데 link대신에 다른 태그를 입력 받아 사용하려면 말씀하신대로 rss 관리 등에서 그 값을 입력 받아서 해당 값으로 getter를 호출해야 하지요. 즉 가능합니다. 하지만 잘못된 테그명 입력시 오류가 날텐데 이를 사용자분들께서 잘 핸들링 하실지 걱정되네요.

**Comment by bulzipke** [comment]
오.. 그렇군요. 
프록시를 적용받을 수 있거나, sni 적용이 가능하면 매우 좋을 것 같긴합니다 :)

또 하나 궁금한게.. 자막 받는 기능도 있던데 혹시 모범(?) RSS 예제가 있으면 참고 하고 싶습니다~

**Comment by tarpha** [comment]
프록시 설정을 넣었으나 rss 대상은 아닙니다. 도커로 실행 시 환경변수에 HTTP_PROXY, HTTPS_PROXY를 설정하면 프록시 기능이 됩니다. 자막 기능은 동일 제목으로 자막이 올라왔을 때 다운받는 기능이므로 RSS에 의존합니다. 
그리고 샘플로 주신 링크는 아마 다운 요청이 안될겁니다. 마그넷 주소나 파일이 바로 보여야 되요.
