### ISSUE TITLE
Feed 내용에 특수문자 제거

### ISSUE THREAD

**Issue by arurung** [tarpha/torrssen2#15]
좋은툴 개발해주셔서 정말 감사드립니다 ^^

사용중에 문의사항이 있습니다.

feed 내용에 대괄호 [] 로 블록이 쌓여져 있으면 해당 내용을 제거하고 가져오고 있습니다.
ex ) [test제목] 영화제목 -> 영화제목

혹시 이 기능이 기본 처리방법인지 궁금합니다.

**Comment by tarpha** [comment]
네 방송사 정보 등이 들어가 있어서 기본 제거합니다.

**Comment by arurung** [comment]
[품번]인 경우가 있어서 자동 다운로드를 걸려고 했는데 방법이 없겠군요 ㅠ

**Comment by tarpha** [comment]
어려운거 아니니 언제 옵션 처리 해드릴께요.

**Comment by tarpha** [comment]
시리즈여부 false 로 하면 보이지 않나요?

**Comment by arurung** [comment]
최초부터 false 로 설정해두었습니다.

**Comment by tarpha** [comment]
시리즈 여부 false 일때 [ 내용 ] 살려놨습니다.
