### ISSUE TITLE
Docker 파일 이관시..

### ISSUE THREAD

**Issue by acras9** [tarpha/torrssen2#17]
안녕하세요 torrssen2 잘쓰다가 이슈가 있어서 문의 드립니다.

기존에 docker로 사용하고 있었는데
Docker를 사용하는 host의 ip가 바뀌고 나니
Torrssen2가 작동을 하지 않네요 ㅠㅜ

혹시 마이그레이션 방법이 없을까요
이미 너무 많은 세팅을 해버려서 막상 다시 세팅하려하니 엄두가 안납니다

**Comment by tarpha** [comment]
db파일만 옮기시거나 volume으로 빼시면 됩니다. 
~/data 안에 있는 .db 파일입니다.
