### ISSUE TITLE
rss 피드

### ISSUE THREAD

**Issue by htogether** [tarpha/torrssen2#19]
아래 사이트를 rss 사이트에 추가해 보면 피드가 제대로 되지 않습니다.
아래 사이트의 문제일까요 아니면 토센의 문제인가요?

https://torrentyo1.com/bbs/board.php?bo_table=entertain 테이블의 rss 주소는

https://torrentyo1.com/bbs/rss.php?bo_table=entertain 인데

tv, drama, movie 모두 안되네요.

**Comment by tarpha** [comment]
해당 RSS를 열어보시면 link부분이 magnet이나 torrent파일의 직접 링크가 아닌 해당 게시물 페이지로 되어 있어 가져오지 못합니다. 재 가공하셔야 할듯 하네요.
