### ISSUE TITLE
다운로드스테이션 지정 후 다운로드 시 “다운로드 요청 실패”

### ISSUE THREAD

**Issue by bg3305** [tarpha/torrssen2#25]
torrssen2 0.9.43에서 기본 다운로드 앱을 다운로드스테이션으로 설정 후 다운로드하면, 다운로드 스테이션에 해당 마그넷이 정상적으로 반영되어 다운로드를 진행함에도 불구하고 “다운로드 요청 실패” 팝업이 뜹니다. 이와 관련한 도커 로그는 생성이 안되어 제공해 드릴 수 없습니다. 참고로 트랜스미션으로 설정했을 때는 문제 없었습니다. 무엇이 문제일까요?

**Comment by tarpha** [comment]
로그를 남겨 주셔야 분석이 가능합니다.

다운로드 스테이션의 경우 제작 시점의 api로 테스트 되엇습니다. 트랜스미션과는 다르게 매끄럽게 동작하지 않기도 하고요.
가능하면 트랜스미션을 권장드립니다.

**Comment by tarpha** [comment]
로컬 테스트 시 말씀하신 현상은 발생하지 않네요.

다운로드 경로가 잘못된건 아니신가요? 다운로드 스테이션의 경우 시놀로지 공유폴더 형식으로  Setting 해주셔야 합니다.

/download or download : OK
/volume1/download: NOT OK

**Comment by bg3305** [comment]
앞서 언급한 바와 같이 지정한 경로로 실제 다운로드까지 되는 반면에 팝업만 요청 실패가 뜨는 상황입니다. 지금 그대로 사용해도 문제는 없지만 팝업이 뜨는 조건 설정이 무언가 잘못되어 있지 않나 해서 문의드린 겁니다.

**Comment by tarpha** [comment]
네 서버 로그나 프론트 로그를 남겨주셔야 분석 가능합니다. 현상으론 분석이 안되요.
그리고 다운로드 스테이션 사용은 추천드리지 않습니다.
팝업이 뜨는 조건은 '잘못된'것이 아니라 api에서 정상 응답을 받지 않았을 경우 발생합니다.

다시한번 말씀드리지만 현상을 말씀주시지 마시고 '로그'를 남겨주세요. 오픈소스 프로젝트에서 이슈처리를 요청하실때는 사용자 관점이 아니라 함께 발전시키는 방향으로 진행되어야 한다고 봅니다.

**Comment by bg3305** [comment]
답변 감사드립니다. 저도 로그를 드리고 싶은데, 시놀로지 로그 센터나 도커 컨테이너 세부 사항에 해당 작업과 관련하여 아무런 로그가 생성되지 않아 드리지 못함이 안타깝습니다. 로그를 볼 수 있는 다른 방법이 있을까요? 본업이 이 쪽 분야가 아니라 기초적인 질문을 드리게 되어 죄송합니다.
