### ISSUE TITLE
/torrssen2/docker/torrssen2-*.jar 부재에 따른 오류

### ISSUE THREAD

**Issue by banyazavi** [tarpha/torrssen2#26]
안녕하세요, torrssen2 잘 쓰고 있습니다. 감사합니다.

금일부터 torrssen2 실행 실패하는 문제가 있어 로그를 살펴보니, 아래와 같은 내용이 있었습니다.

```
Error: Unable to access jarfile torrssen2.jar
cp: can't stat '/torrssen2/docker/torrssen2-*.jar': No such file or directory
```

코드 업데이트 후 `docker` 디렉토리에 jar 파일을 깜빡하신 것 같습니다.

확인 부탁드립니다. 감사합니다.

**Comment by tarpha** [comment]
다단계 build 파일을 만드면서 기존 자동 업데이트를 사용하시는 분들을 깜빡했군요. 넣어놨습니다.
