### ISSUE TITLE
텔레그램 알림 잘 동작하나요?

### ISSUE THREAD

**Issue by htogether** [tarpha/torrssen2#29]
데비안 부스터에 도커로 사용중입니다.

테스트 알림은 잘 오는데 트랜스미션 완료시 알림이 거의 오지 않습니다.

어떤부분을 체크해야 할까요?

**Comment by tarpha** [comment]
callback을 사용하시거나 옵션을 바꾸셔야합니다. 

https://m.clien.net/service/board/cm_nas/14586908?combine=true&q=torrssen%20텔레그램&p=0&sort=recency&boardCd=&isBoard=false
