### ISSUE TITLE
트랜스미션 완료 이동 안됨

### ISSUE THREAD

**Issue by poohehe** [tarpha/torrssen2#34]
트랜스미션을 설정해서 다운로드가 완료된 이후에 방송 제목의 폴더로 파일이 이동되어야 하는데 이동되지 않습니다.
찾아보니 다운로드는 완료 되었는데 incomming 폴더에 남아있어서 처리가 안되는 것 같습니다.
직접 마그넷을 추가하여 다운로드를 하였을 때 incomming 폴더에서 완료 폴더로 이동된 것을 보면 트랜스미션의 이상은 아닌 것 같습니다.

트랜스미션은 Transmission 3.00이고 다운로드 완료 검사 주기는 1분으로 설정되어 있습니다.
확인해주시면 고맙겠습니다.

**Comment by tarpha** [comment]
트랜스미션은 해당 프로젝트와 무관합니다.

**Comment by tarpha** [comment]
해당 이슈를 처리하지 않는 이유는

1. 수십번 말씀드린 현상만이 있으며 (로그 없음)
2. 사용자 별로 다른 환경 설정에 따른 문제로 보이고
3. 트랜스미션 연동 API시 경로만 지정해 주고 처리는 맡기기 때문입니다.
