### ISSUE TITLE
RSS 주소 인코딩 문제

### ISSUE THREAD

**Issue by reikop** [tarpha/torrssen2#4]
https://torrentwal.com/bbs/rss.php?k=Next&b=

위 주소로 등록했을때 RSS한글이 깨지는 현상이 있네요
설정에서 인코딩을 변경할수 있다면 좋겠습니다.

**Comment by tarpha** [comment]
확인이 늦었네요. 크롬에서 해당 rss를 열어도 인코딩이 다 깨지는걸 봐서 좀 더 보겠습니다.

**Comment by tarpha** [comment]
소스 내에서 인코딩을 바꿔도 제대로 안보이네요.
사이트에서 제대로 뿌려주거나 위에 언급한 snoopy 등으로 한번 wrapping 해서 뿌려줘야 할 것 같네요.

**Comment by jshsakura** [comment]
토렌트왈의경우 php에서한번더 인코딩합니다.
