### ISSUE TITLE
torrent 시드 파일 한글깨짐 현상.

### ISSUE THREAD

**Issue by shamid84** [tarpha/torrssen2#41]
안녕하세요. 만들어 주신 프로그램 덕분에 편안히 드라마를 잘 받고 있습니다.

사용하다 보니 한가지 문제가 발생하여 문의 드립니다.

토렌트 사이트에서 토렌트시드 파일들을 rss로 생성하여 사용중입니다.

rss를 읽어 들여 리스트로 표시 되는부분은 잘 작동하는데 다운받으면

시드 파일의 한글이 깨져서 나옵니다.

시드 파일이 깨져서 나오다 보니 다운은 잘 받아 지는데 자동정리와 다운로드 완료 확인 부분에서 매칭에 문제가 발생하고 있습니다.

환경변수에서 영어로 된걸 한글로 바꾸어도 봤는데 다른방식으로 깨질뿐 해결이 안되고 있습니다.

혹시나 싶어 rss를 utorrent와 다운로드스테이션에서 실행해보았지만 시드파일의 한글이 깨지지 않고 다운 받아집니다.

도움 요청 들입니다.

글자가 깨지는건 다음과 같습니다.

시드 파일 : ìëª¨ë¥´ íí° - ì¬ëíë¼, ì§ê¸.E37.210601.720p.H264-F1RST.mp4.torrent

다운받은 파일 : 아모르 파티 - 사랑하라, 지금.E37.210601.720p.H264-F1RST.mp4
![캡처](https://user-images.githubusercontent.com/85170284/120324407-8c4b1500-c321-11eb-84b9-1d8c9534da2b.JPG)

**Comment by tarpha** [comment]
transmission은 torrent 파일링크로 동적하지 않습니다. 따라서 파일만 http로 동작하도록 만들긴 했는데 이후 사용하고 있지 않습니다. 마그넷이 있는 feed 로 사용하시길 추천드립니다.
