### ISSUE TITLE
torr.php 에서 생성된 rss 가 보이지 않습니다.

### ISSUE THREAD

**Issue by htogether** [tarpha/torrssen2#49]
rss 가 생성되는건 브라우저에서 확인했습니다.

하지만 토센에서 읽어오지 않는건지 리스트가 보이지 않네요. 혹시나 해서 torr 에서 저장된 db 를 초기화하고 기다려봐도 리스트가 보이지 않네요.
뭐가 문제일까요?

**Comment by tarpha** [comment]
이슈는 문의응대 용도가 아니며 오픈소스 프로젝트의 취지에 맞지 않는 질문입니다.

**Comment by htogether** [comment]
ERROR [thread-async-1] com.tarpha.torrssen2.service.RssLoadService: Received fatal alert: protocol_version

로그 기록
