### ISSUE TITLE
토렌트 파일 Feed 사용이 불가능한가요?

### ISSUE THREAD

**Issue by kimpig** [tarpha/torrssen2#50]
안녕하세요.
먼저 좋은 프로그램 개발해주셔서 감사합니다.

https://nyaa.si/?page=rss
예전부터 이 RSS로 사용을 하고 있었는데, 근 2주 전부터 이 RSS로 다운이 되지가 않더라고요.
목록까지는 뜨지만 다운로드를 누르면 다운로드 실패라고 뜨네요.

또 다른 RSS는 잘 동작해서 살펴보니 이 RSS는 link에 torrent 파일을 사용하더라고요.
토렌트 파일로 된 Feed는 사용이 불가능한건지 궁금합니다.
2주 전까지는 사용에 문제가 없었는데, 이 RSS 사이트에 문제가 있는것으로 생각하면 될까요?

질문이 미숙한점 죄송합니다;

**Comment by tarpha** [comment]
로그 없는 이슈는 응대하지 않습니다. 오픈소스 프로젝트이므로 트러블 슈팅이 가능한 내용이 필요합니다.
