### ISSUE TITLE
내장 RSS가 에러가 나면서 동작하지 않아요~

### ISSUE THREAD

**Issue by caesarju** [tarpha/torrssen2#54]
안녕하세요? 좋은 프로그램 만들어 주셔서 감사드립니다.
torrssen2의 내장 RSS를 이용해 보고자 하였으나, 첨부와 같이 에러가 나면서 동작이 되지 않네요. ㅠ

다른 설정이 필요한지요? 로그를 첨부합니다.
감사합니다.

[_torrssen2_logs.txt](https://github.com/tarpha/torrssen2/files/7965481/_torrssen2_logs.txt)

**Comment by tarpha** [comment]
현재 수정되었습니다.
