### ISSUE TITLE
[의견] rss description 처리

### ISSUE THREAD

**Issue by byorial** [tarpha/torrssen2#6]
RSS feed 생성을 따로 처리하고 있는데 

description 에 해당 해당 item의 정보를 획득한 url을 기록하고 있습니다.

torrssen2 에서 보여줄때 description 도 보여주고 http(s) 링크를 포함하는 경우 처리해주는 

기능이 있으면 좋을 것 같네요. 

정보를 못얻어 오는 경우에 클릭해서 상세 내용을 확인할 수 있을 겉 같네요.

**Comment by tarpha** [comment]
ui를 단순화 하고 다운로드 액션만 이루어질 수 있도록 구성한 내용이라
말씀하신 부분 고민해 보겠습니다. 특정 링크를 누르면 새 창으로 열리는건 문제 없을 것 같네요.

**Comment by tarpha** [comment]
0.9.27버전에 기능은 추가해 놓았습니다. 그런데 description에 link가 있는 feed가 많지는 않네요.
