### ISSUE TITLE
[오류] RSS 사이트 저장/갱신 오류

### ISSUE THREAD

**Issue by byorial** [tarpha/torrssen2#7]
RSS 사이트관리에 등록한 주소가 자꾸 이전에 등록했던 주소로 바뀌는 증상이 있습니다. 

번경하여 등록하면 잘 되다가.. 어느 시점에 전부 바뀌어 버리는데 

RSS 피드가 제대로 안올라와서 확인해 보면 이전주소로 바뀌어 있더라구요 

정확한 원인은 알 수 없으나 아마 RSS 사이트 주소 변경 - 저장 후에 

RSS 버튼 눌러서 체크 또는 체크해제 한상태에서 다시 RSS사이트 주소 관리 화면 들어가 보면 

바뀌어 있습니다.

**Comment by tarpha** [comment]
확인해보겠습니다. 임시 방편으로는 수정 대신 삭제 후 재등록 하면 위 오류는 발생하지 않을거 같네요.

**Comment by tarpha** [comment]
0.9.26 버전에서 수정되었습니다.
