### ISSUE TITLE
RSS 데이터 갱신 안되는 현상이 있습니다. 

### ISSUE THREAD

**Issue by byorial** [tarpha/torrssen2#8]
RSS 아이콘을 통해 갱신요청을 누르면 

목록이 갱신 되었습니다. 라고 완료 메시지는 뜨는데 실제 갱신은 안되네요. 

실제 RSS사이트 관리에 등록한 주소로 직접 접근해보면 

torrssen2에서 뿌려주는 데이터랑 다르네요. 
![RSS](https://user-images.githubusercontent.com/26082983/64681521-d5f32c80-d4ba-11e9-911c-58d1f6175fca.png)

**Comment by tarpha** [comment]
제목은 파싱해서 그렇습니다. 같은 데이터 같네요. 앞에 파일 아이콘 있네요. 파싱을 원치 않으시면 시리즈여부를 false로 바꿔주세요.
