### ISSUE TITLE
pubData  처리 이슈

### ISSUE THREAD

**Issue by byorial** [tarpha/torrssen2#9]
얼마전부터 RSS의 pubDate를 제대로 처리하지 못하는 듯 합니다. 

[원본  RSS] 
`<item> <title>멜로가 체질.E12.190914.720p NEXT.mp4</title> <link> magnet:?xt=urn:btih:3252218035f0a0f416ff8dfbae20faa0c80624b7 </link> <description/> <pubDate>Sun, 15 Sep 2019 00:48:54 +0900</pubDate> </item>`

[torrssen2 조회결과]
`star done 멜로가 체질
S01 E12 — 190914 720p NEXT
드라마 13 분전`

실제 조회시간은 9/15 19시 5분경 인데 13분 전으로 나오네요.

**Comment by tarpha** [comment]
pub date 기준으로 가져오지 않고 db insert 시간 기준으로 가져옵니다.
pubDate tag는 사용하고 있지 않습니다.
